# Generated by Django 6.1 on 2026-08-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesurement',
            new_name='Measurement',
        ),
    ]
