def SOMEFUNCTIONNAMETHATISLONG(SOMETEXTGIVEN, SOMEOTHERTEXTHERETOO):
    return SOMETEXTGIVEN + ", and also: " + SOMEOTHERTEXTHERETOO
def THISISMAINFUNCTION():
    HARDTOARGUE = "Jesus is LORD"
    EVERYKNEEWILLBOW = "Worship Him only"
    SOLIDEOGLORIA = SOMEFUNCTIONNAMETHATISLONG(HARDTOARGUE, EVERYKNEEWILLBOW)
    print(SOLIDEOGLORIA)
THISISMAINFUNCTION()
