# Generated by Django 5.1.3 on 2024-11-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=217)),
                ('password', models.CharField(max_length=127)),
                ('balance', models.PositiveIntegerField()),
                ('limit', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('C', 'Client'), ('M', 'Manager')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('S', 'Single'), ('P', 'Periodic')], default='S', max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.user')),
            ],
        ),
    ]
