# Generated by Django 5.1.3 on 2024-11-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='next_payout',
        ),
    ]
