# Generated by Django 5.1.3 on 2024-11-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_date_payment_next_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='next_payout',
            new_name='date',
        ),
    ]
