[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
    "tensorflow>=2.21.0",
    "tqdm>=4.70.1",
    "transformers[torch]>=5.17.0",
    "wordcloud>=1.9.6",
]
