# Generated by Django 5.1.3 on 2024-11-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='when',
            new_name='timestamp',
        ),
    ]
