# Generated by Django 5.1.3 on 2024-11-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_when_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('SNG', 'Single'), ('PER', 'Periodic')], default='SNG', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='operation',
            field=models.CharField(choices=[('WIT', 'Withdrawal'), ('DEP', 'Deposit')], default='WIT', max_length=3),
            preserve_default=False,
        ),
    ]
