# Generated by Django 5.1.3 on 2024-11-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payment_kind_alter_payment_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('period', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], max_length=12)),
                ('next_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.client')),
            ],
        ),
    ]
