# Generated by Django 5.1.3 on 2024-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_periodicpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicpayment',
            name='next_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
