# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "D:/repos/university/year1-term2/OOP/lb9/build-calendar_app-Boot2Qt_6_5_0_Intel_NUC-Debug/.qtc/package-manager/auto-setup.cmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_SYSROOT" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/skylake-64-poky-linux" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER_TARGET" "x86_64-poky-linux" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_COMPILER_TARGET" "x86_64-poky-linux" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_COMPILER" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/x86_64-w64-mingw32/usr/bin/x86_64-poky-linux/x86_64-poky-linux-g++.exe" CACHE "STRING" "" FORCE)
set("CMAKE_C_COMPILER" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/x86_64-w64-mingw32/usr/bin/x86_64-poky-linux/x86_64-poky-linux-gcc.exe" CACHE "STRING" "" FORCE)
set("CMAKE_PREFIX_PATH" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/skylake-64-poky-linux/usr" CACHE "STRING" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/x86_64-w64-mingw32/usr/bin/qmake.exe" CACHE "STRING" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/x86_64-w64-mingw32/usr/lib/cmake/Qt6/qt.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_MAKE_PROGRAM" "D:/programs/QT_CREATOR/6.5.0/Boot2Qt/intel-skylake-64/toolchain/sysroots/x86_64-w64-mingw32/usr/bin/ninja.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)