# Generated by Django 5.1.3 on 2024-11-18 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0003_rename_user_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Account',
        ),
    ]
