# Generated by Django 5.1.3 on 2024-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0005_remove_account_user_account_name_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='period',
            field=models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], default=None, max_length=5),
        ),
    ]
