# Generated by Django 5.1.3 on 2024-11-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0006_pay_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
