# Generated by Django 5.1.3 on 2024-11-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pays', '0007_remove_pay_user_delete_account_delete_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('limit', models.PositiveBigIntegerField(default=0)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
