# Generated by Django 5.1.3 on 2024-11-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
