# Generated by Django 5.2 on 2025-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunch',
            name='processed',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bunch',
            name='stage',
            field=models.CharField(choices=[('JU', 'Juice'), ('RS', 'Raisins'), ('GR', 'Grapes'), ('JL', 'Jelly'), ('WN', 'Wine')], default=None, max_length=7),
        ),
    ]
