# Generated by Django 5.2 on 2025-04-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0002_bunch_processed_bunch_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='stage',
            field=models.CharField(choices=[('NO', 'Processing...'), ('JU', 'Juice'), ('RS', 'Raisins'), ('GR', 'Grapes'), ('JL', 'Jelly'), ('WN', 'Wine')], default=None, max_length=7),
        ),
    ]
