# Generated by Django 5.2 on 2025-04-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0003_alter_bunch_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='stage',
            field=models.CharField(blank=True, choices=[('JU', 'Juice'), ('RS', 'Raisins'), ('GR', 'Grapes'), ('JL', 'Jelly'), ('WN', 'Wine')], max_length=7),
        ),
    ]
