# Generated by Django 5.2 on 2025-04-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0004_alter_bunch_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunch',
            name='processed',
        ),
        migrations.AlterField(
            model_name='bunch',
            name='stage',
            field=models.CharField(blank=True, choices=[('Juice', 'Juice'), ('Wine', 'Wine'), ('Grapes', 'Grapes'), ('Raisins', 'Raisins'), ('Jelly', 'Jelly')], max_length=7),
        ),
    ]
