# Generated by Django 5.2 on 2025-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0005_remove_bunch_processed_alter_bunch_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='outside',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='shape',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='sugar',
            field=models.BooleanField(default=False),
        ),
    ]
