# Generated by Django 5.2 on 2025-05-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0006_alter_bunch_color_alter_bunch_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
    ]
