# Generated by Django 5.2 on 2025-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0007_alter_bunch_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='sugar',
            field=models.BooleanField(default=False),
        ),
    ]
