# Generated by Django 6.0 on 2025-12-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='HistoryItem',
        ),
        migrations.RenameField(
            model_name='historyitem',
            old_name='query_text',
            new_name='text',
        ),
    ]
