SN=SNnew;
SN=SNaddORnode(SN, 'high','normal','acute', 'weak','in stomach', 'in spine');
SN=SNaddANDnode(SN, 'patient', 'symptoms', 'temperature', 'pain type', 'pain');
SN=SNaddANDnode(SN, 'diagnosis', 'apendicitis', 'pielonefrit', 'acute apendicitis'); 
SN=SNaddANDnode(SN, 'acute pielonefrit', 'chronic apendicitis', 'chronic pielonefrit');
SN=SNaddrelation(SN, 'patient', 'has', 'symptoms');
SN=SNaddrelation(SN, 'patient', 'has', 'diagnosis');
SN=SNaddrelation(SN, 'symptoms', 'type', 'temperature');
SN=SNaddrelation(SN, 'symptoms', 'type', 'pain type');
SN=SNaddrelation(SN, 'symptoms', 'type', 'pain');
SN=SNaddrelation(SN, 'diagnosis', 'type', 'acute apendicitis');
SN=SNaddrelation(SN, 'diagnosis', 'type', 'acute pielonefrit');
SN=SNaddrelation(SN, 'diagnosis', 'type', 'chronic apendicitis');
SN=SNaddrelation(SN, 'diagnosis', 'type', 'chronic pielonefrit');
SN=SNaddrelation(SN, 'temperature', 'type', 'high');
SN=SNaddrelation(SN, 'temperature', 'type', 'normal');
SN=SNaddrelation(SN, 'pain type', 'type', 'acute');
SN=SNaddrelation(SN, 'pain type', 'type', 'weak');
SN=SNaddrelation(SN, 'pain', 'type', 'in stomach');
SN=SNaddrelation(SN, 'pain', 'type', 'in spine');
SN=SNaddrelation(SN, 'in stomach','include', 'apendicitis');
SN=SNaddrelation(SN, 'in spine', 'include', 'pielonefrit');
SN=SNaddrelation(SN, 'apendicitis', 'include', 'acute apendicitis');
SN=SNaddrelation(SN, 'apendicitis', 'include', 'chronic apendicitis');
SN=SNaddrelation(SN, 'pielonefrit', 'include', 'acute pielonefrit');
SN=SNaddrelation(SN, 'pielonefrit', 'include', 'chronic pielonefrit');
SN=SNaddrelation(SN, 'high', 'include', 'acute apendicitis');
SN=SNaddrelation(SN, 'normal', 'include', 'chronic apendicitis');
SN=SNaddrelation(SN, 'high' , 'include', 'acute pielonefrit');
SN=SNaddrelation(SN, 'normal', 'include', 'chronic pielonefrit');
SN=SNaddrelation(SN, 'acute', 'include', 'acute apendicitis');
SN=SNaddrelation(SN, 'weak', 'include', 'chronic apendicitis');
SN=SNaddrelation(SN, 'acute','include', 'acute pielonefrit');
SN=SNaddrelation(SN, 'weak', 'include', 'chronic pielonefrit');
% SNplot(SN, 'circle'); 
% SNplot(SN, 'random'); 
SNplot(SN, 'hierarchy'); 
% hold on;
SN1=SN;
SN1=SNdelnode(SN1, 'normal', 'in spine', 'weak','apendicitis', 'pielonefrit', 'acute apendicitis');
SN1=SNdelnode(SN1, 'acute pielonefrit', 'chronic apendicitis', 'chronic pielonefrit');
SN1=SNaddANDnode(SN1, '?');
SN1=SNaddrelation(SN1, 'diagnosis', 'type', '?')
figure;
% SNplot(SN1, 'hierarchy');
SNplot(SN1, 'circle'); 
% SNplot(SN1, 'random'); 
SNfind(SN, SN1)

