/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personal.second_vars;

/**
 *
 * @author seesm
 */
public class VariablesFrame extends javax.swing.JFrame {
    int integerVar = 1;
    long longVar = 1;
    float floatVar = 1.0f;
    double doubleVar = 1.0;

    /**
     * Creates new form VariablesFrame
     */
    public VariablesFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessageWindow = new javax.swing.JPopupMenu();
        intButton = new javax.swing.JButton();
        longButton = new javax.swing.JButton();
        floatButton = new javax.swing.JButton();
        doubleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intButton.setText("int");
        intButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intButtonActionPerformed(evt);
            }
        });

        longButton.setText("long");
        longButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longButtonActionPerformed(evt);
            }
        });

        floatButton.setText("float");
        floatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatButtonActionPerformed(evt);
            }
        });

        doubleButton.setText("double");
        doubleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(intButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(longButton)
                                .addGap(18, 18, 18)
                                .addComponent(floatButton)
                                .addGap(18, 18, 18)
                                .addComponent(doubleButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(intButton)
                                        .addComponent(longButton)
                                        .addComponent(floatButton)
                                        .addComponent(doubleButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_intButtonActionPerformed
        this.integerVar += 1;
        try {
            MessageWindow.remove(0);
        } catch (Exception e) {
            assert true;
        }
        MessageWindow.add("Int: " + Integer.toString(this.integerVar));
        MessageWindow.show(this, WIDTH, WIDTH);
    }// GEN-LAST:event_intButtonActionPerformed

    private void longButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_longButtonActionPerformed
        this.longVar += 1;
        try {
            MessageWindow.remove(0);
        } catch (Exception e) {
            assert true;
        }
        MessageWindow.add("Long: " + Long.toString(this.longVar));
        MessageWindow.show(this, WIDTH, WIDTH);
    }// GEN-LAST:event_longButtonActionPerformed

    private void floatButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_floatButtonActionPerformed
        this.floatVar += 0.1f;
        try {
            MessageWindow.remove(0);
        } catch (Exception e) {
            assert true;
        }
        MessageWindow.add("Float: " + Float.toString(this.floatVar));
        MessageWindow.show(this, WIDTH, WIDTH);
    }// GEN-LAST:event_floatButtonActionPerformed

    private void doubleButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doubleButtonActionPerformed
        this.doubleVar += 0.1;
        try {
            MessageWindow.remove(0);
        } catch (Exception e) {
            assert true;
        }
        MessageWindow.add("Double: " + Double.toString(this.doubleVar));
        MessageWindow.show(this, WIDTH, WIDTH);
    }// GEN-LAST:event_doubleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VariablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VariablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VariablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VariablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VariablesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu MessageWindow;
    private javax.swing.JButton doubleButton;
    private javax.swing.JButton floatButton;
    private javax.swing.JButton intButton;
    private javax.swing.JButton longButton;
    // End of variables declaration//GEN-END:variables
}
