import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex max-w-3xl mx-auto justify-between border-2 p-3 my-3">
          <Link href="/tools" className="hover:underline">
            Tools
          </Link>
          <Link href="/" className="hover:underline">
            Field
          </Link>
          <Link href="/shop" className="hover:underline">
            Shop
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
