(defun MainLayer ()
  (command "LINETYPE" "S" "BYLAYER" "" "LWEIGHT" 0.5 "" "COLOR" "white")
)

(defun AxisLayer ()
  (command "LINETYPE" "S" "CENTER" "" "LWEIGHT" 0.3 "" "COLOR" 40)
)

(defun SizeLayer ()
  (command "LINETYPE" "S" "BYLAYER" "" "LWEIGHT" 0.3 "" "COLOR" 140)
)

(defun c:gasket ()
  ; axises
  (setq top_left_vertical_axis_point (list 0 75))
  (setq bottom_left_vertical_axis_point (list 0 -75))
  (setq top_right_vertical_axis_point (list 200 45))
  (setq bottom_right_vertical_axis_point (list 200 -45))
  (setq left_horizontal_axis_point (list -75 0))
  (setq right_horizontal_axis_point (list 245 0))
  ; dimensions
  (setq select_left_inner_circle (list 34.1107 30.3610))
  (setq select_left_outer_circle (list -48.3743 49.6739))
  (setq left_inner_circle_dimension_point (list -70 -50))
  (setq left_outer_circle_dimension_point (list -40 80))
  (setq select_right_inner_circle (list 182.6092 9.5745))
  (setq select_right_outer_circle (list 239.0539 -10.1209))
  (setq right_inner_circle_dimension_point (list 250 -40))
  (setq right_outer_circle_dimension_point (list 240 40))
  (setq select_left_eighty_dimension_point (list 120 -60))
  (setq eighty_horizontal_dimension_point (list 200 -70))
  (setq two_hundred_horizontal_dimension_point (list 200 -90))
  (setq select_top_vertical_dimension (list 120 60))
  (setq select_bottom_vertical_dimension (list 120 -60))
  (setq vertical_dimension_point (list 270 60))

  (command "grid" "OFF")
  (command "OSNAP" "OFF")
  (command "SNAP" "OFF")
  (command "LWDISPLAY" 1)
  (AxisLayer)
  (command "LINE" top_left_vertical_axis_point bottom_left_vertical_axis_point "")
  (command "LINE" top_right_vertical_axis_point bottom_right_vertical_axis_point "")
  (command "LINE" left_horizontal_axis_point right_horizontal_axis_point "")
  (MainLayer)
  (command "ZOOM" "All")
  (command "CIRCLE" (list 0 0) "D" 92)
  (command "CIRCLE" (list 0 0) "D" 140)
  (command "CIRCLE" (list 200 0) "D" 40)
  (command "CIRCLE" (list 200 0) "D" 80)
  (command "PLINE" (list 200 40) (list 120 40) (list 120 60) (list 36 60) "")
  (command "MIRROR" (list 110 60) "" (list 200 0) (list 400 0) "N")
  (command "trim" (list 70 60) (list 70 -60) "" (list 63.1369 29.7627) (list 161.2380 10.5113) "")
  (SizeLayer)
  (command "dimtxt" 7)
  (command "dimasz" 7)
  (command "dimdiameter" select_left_inner_circle left_inner_circle_dimension_point)
  (command "dimdiameter" select_left_outer_circle left_outer_circle_dimension_point)
  (command "dimdiameter" select_right_inner_circle right_inner_circle_dimension_point)
  (command "dimradius" select_right_outer_circle right_outer_circle_dimension_point)
  (command "dimhorizontal" select_left_eighty_dimension_point bottom_right_vertical_axis_point eighty_horizontal_dimension_point)
  (command "dimhorizontal" eighty_horizontal_dimension_point bottom_left_vertical_axis_point two_hundred_horizontal_dimension_point)
  (command "dimvertical" select_top_vertical_dimension select_bottom_vertical_dimension vertical_dimension_point)
)